### ISSUE TITLE
Missing shader files: VidMetalLib.metallib

### ISSUE THREAD

**Issue by dream5788** [endavid/VidEngine#5]
Missing shader files: VidMetalLib.metallib

**Comment by endavid** [comment]
As stated in the Readme, you need to build those first, using the provided build script.
> Use the provided build.sh, because I can't figure out how to get the shaders in VidMetalLib to get linked to the correct location from Xcode... 😅

I don't know how to set up Xcode so this is done automatically. If you know how, please send me a pull request with the updated project file.
